name: build/publish docker & singularity (cvmfs) images


on:
  workflow_dispatch:
    inputs:
      replace_all:
        description: "Delete all repo's images on CVMFS, then build?"
        required: false
        default: false
        type: boolean


concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}


jobs:

  image:
    runs-on: ubuntu-latest
    steps:
      - name: Determine action
        id: set_action
        run: |
          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
          
          if [[ "${{ github.event.inputs.replace_all }}" == "true" ]]; then
            echo "action=CVMFS_REMOVE_THEN_BUILD" >> "$GITHUB_OUTPUT"
          else
            echo "action=CVMFS_BUILD" >> "$GITHUB_OUTPUT"
          fi

      - uses: WIPACrepo/wipac-dev-publish-image-action@main
        with:
          image: ghcr.io/observation-management-service/ewms-condor-benchmarking
          action: ${{ steps.set_action.outputs.action }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}
          gh_cvmfs_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          cvmfs_dest_dir: ewms/observation-management-service/
          cvmfs_remove_tags: '${{ github.ref_name }}-[SHA]'
