name: build/publish docker & singularity (cvmfs) images


on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      do_delete:
        description: 'Delete from CVMFS instead of build?'
        required: false
        default: false
        type: boolean
      platform:
        description: 'Platform to build docker image'
        required: false
        default: 'linux/amd64'
        type: choice
        options:
          - linux/amd64
          - linux/arm64
  delete:
    branches:
      - '**'


env:
  DEFAULT_PLATFORM: linux/amd64  # matches 'workflow_dispatch.inputs.platform.default' above


concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}


jobs:

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: WIPACrepo/wipac-dev-publish-image-action@main
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # so job can git push
          image: ghcr.io/observation-management-service/ewms-condor-benchmarking
          action: ''
          cvmfs_dest_dir: ewms/observation-management-service/
          free_disk_space: false
          build_platform: ${{ github.event.inputs.platform || env.DEFAULT_PLATFORM }}
